version: '3.8'
services:
  rabbitmq:
    container_name: "rabbitmq"
    image: 3.8-management-alpine
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=slim
    ports:
      #RabbitMQ instance
      - '5672:5672'
      #web instance
      - '15672:15672'

